FROM maven:3.9.6-eclipse-temurin-17
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests --no-transfer-progress clean package
CMD ["java", "-jar", "target/hello-app-1.0-SNAPSHOT-jar-with-dependencies.jar"]
